#include <iostream>
using namespace std;

int main() {
    int n, original, digit, reverse = 0;

    cout << "Enter a number: ";
    cin >> n;

    original = n;

    while (n > 0) {
        digit = n % 10;
        reverse = reverse * 10 + digit;
        n = n / 10;
    }

    if (reverse == original)
        cout << "Palindrome Number";
    else
        cout << "Not a Palindrome Number";

    return 0;
}
